# Ejemplo de tres en raya con easyAI
## A continuacion importaremos las librerias

In [1]:
from easyAI import TwoPlayersGame, Human_Player, AI_Player, Negamax
import numpy as np

In [ ]:
Procederemos a realizar una herencia de la clase TwoPlayersGame y creamos la clase tres en raya

In [ ]:
class TresEnRaya(TwoPlayersGame):
    
    def __init__(self,nplayers): ##Constructor de la clase
        self.tablero = np.zeros((3,3),dtype = int) ## Creamos un tablero de 3x2
        self.nplayer = 1
        self.mapa = {}
        cont = 1 ##Creamos un contador para recorrer el mapa 
        for i in range(len(self.tablero)): #Inicializa os el mapa
            for j in range(len(self.tablero)):
                self.mapa[cont]=(i,j)
                cont+=1
                
        #print(self.mapa) #Imprimimos el mapa de ser necesario
        self.players = nplayers
        
    #Definimos los posibles movimientos
    def possible_moves(self):
        moves = []
        cont = 1
        for i in range(len(self.tablero)):
            for j in range(len(self.tablero)):
                if self.tablero[i][j] == 0:
                    moves.append(cont)
                cont+=1
                
        #print(moves)
        return moves
    
    def make_move(self,casillero): #Realizar los movimientos
        pos = self.mapa[casillero]
        self.tablero[pos[0]][pos[1]] = self.nplayer
        
    def unmake_move(self,casillero):
        pos = self.mapa[casillero]
        self.tablero[pos[0]][pos[1]] = 0
        
    def lose(self): #Verificar si gana o pierde
        for i in range(len(self.tablero)):
            if np.all(self.tablero[i,:]==self.nopponent,axis = 0) or np.all(self.tablero[:,i]==self.nopponent,axis = 0):
                return True
        
        #Diagonal principal
        if self.tablero[0][0]==self.nopponent and self.tablero[1][1]==self.nopponent and self.tablero[2][2]==self.nopponent:
            return True
        #Diagonal secundario
        if self.tablero[2][0]==self.nopponent and self.tablero[1][1]==self.nopponent and self.tablero[0][2]==self.nopponent:
            return True
        
        return False
    
 
    def show(self): #Cada iteracion muestra el tablero
        print(self.tablero)
        
      
    def scoring(self):
        return -100 if self.lose() else 0

        
    def is_over(self): #Validadmos si tiene mas movimientos o pierde
        return (self.possible_moves() == [] or self.lose())
            
    
if __name__=="__main__": #Main - ejecutar el algoritmo
    ai_algo = Negamax(6)
    tresenraya = TresEnRaya([Human_Player(),AI_Player(ai_algo)])
    tresenraya.play()

{1: (0, 0), 2: (0, 1), 3: (0, 2), 4: (1, 0), 5: (1, 1), 6: (1, 2), 7: (2, 0), 8: (2, 1), 9: (2, 2)}
[[0 0 0]
 [0 0 0]
 [0 0 0]]
